let state = {
	tradeList: [],
	selectIds: '',
	levelIds: '',
	levelList: [],
	currentLevelList: [],
	resizeCount: 0,
	hasMenu: false,
	fxylb: '',
	fxySum: '',
	riskPoints: [],
	industry: {
		dm:"xuexiao",
		fxylbmc:"学校",
		icon:null,
		id:16,
		parent_id:50,
		selected:false,
		sffj:1,
		tckdj: 0,
		showChildren:false,
		yc:0,
	},
	industryList: [{
		dm:"xuexiao",
		fxylbmc:"学校",
		icon:null,
		id:16,
		parent_id:50,
		selected:false,
		sffj:1,
		tckdj: 0,
		showChildren:false,
		yc:0,
	}],
	path: {
		chuanboxiuzaoqiye: 'cbxz',
		zhuanyeshichang: 'zysc',
		tiyuchangguan: 'tycg',
		yanglaoyuanshehuifuli: 'nurs',
		jiayouzhan: 'jyz',
		yiyuan: 'hospital',
		weihuomatou: 'whmt',
		weixianhuaxuepinshiyongqiye: 'wxhxp_sy',
		weixianhuaxuepinchucunqiye: 'wxhxp_cc',
		weixianhuaxuepinshengchanqiye: 'wxhxp_sc',
		weixianhuowuyunshu: 'wxhwys',
		shangmaozongheti: 'smzht',
		chengshiqiaoliang: 'csql',
		chengshisuidao: 'cssd',
		tianranqichangzhan: 'trqcz',
		xuexiao: 'school',
		zongjiao: 'religion',
		keyunmatou: 'kymt',
		binguanjiudian: 'bgjd',
		jianzhushigong: 'jzsg',
		wenhuayulechangsuo: 'whylcs',
		lyuyoubaoche: 'lybc',
		lyuyouchangsuo: 'travel',
		xingjijiudian: 'xjjd',
		puhuomatou: 'phmt',
		minbaoqiye: 'mbqy',
		shuikudaba: 'skdb',
		shepentuqiye: 'sptqy',
		sheanzhilengqiye: 'sazl',
		shebaofenchenqiye: 'sbfc',
		yehuashiyouqichangzhan: 'yhsyqcz',
		zhatuxiaonachang: 'ztxnc',
		yanhuabaozhushengchanqiye: 'yhbz_sc',
		yanhuabaozhujingyingqiye: 'yhbz_jy',
		kuangshanqiyedixiakuang: 'ksqy_dxk',
		kuangshanqiyeweikuangku: 'ksqy_wkk',
		kuangshanqiyelutiankuang: 'ksqy_ltk',
		wangba: 'wb',
		jinshuyelianqiye: 'jsyl',
		changtukeyun: 'ctky',
		canyinchangsuo: 'cycs',
		gaocengzhuzhai: 'gczz',
		gaocenggonggongjianzhu: 'gcggjz',
		chengzhenranqi: 'czrq',
		changshuguanxianshuqi: 'csgxsq',
		changshuguanxianshuyou: 'csgxsy',
		renfanggongchengdianwei: 'rfgc',
		zhongyaojingjimubiaodianwei: 'zyjjmb',
		fangkongjingbaoqidianwei: 'fkbjq',
		shusanjidi: 'ssjd',
		ditie: 'dt',
		ditiejianshe: 'dtjs',
		ditieyunxing: 'dtyx',
		zadao: 'zd',
		shuishanghuoyun: 'sshy',
		gonglukeyunzhan: 'glkyz',
		weifang: 'wf',
		huapo: 'hp',
		diwayilaodidai: 'dwyldd',
		dizhizaihaiyinhuandian: 'dzzhyhd',
    yingjijiuyuanduiwu: 'yjjydw',
    yingjijiuyuanzhuangbei: 'yjjyzb',
    shehuiyingjililiang: 'shyjll',
    binanchangsuo: 'bncs'
	}
}

export default state
